import { DataProps } from "./columns";

export const data: DataProps[] = [
  {
    id: 1,
    card: {
      name: "NUBANK [ANT]",
      avatar: "NUBANK",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 14.120,30",
    status: "paid",
    action: null,
  },
  {
    id: 2,
    card: {
      name: "RIACHUELO [AUG]",
      avatar: "RIACHUELO",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 145,12",
    status: "paid",
    action: null,
  },
  {
    id: 3,
    card: {
      name: "SANTANDER [4054]",
      avatar: "SANTANDER",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 112,82",
    status: "paid",
    action: null,
  },
  {
    id: 4,
    card: {
      name: "NOVÜ CARD",
      avatar: "NOVUCARD",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 145,12",
    status: "paid",
    action: null,
  },
  {
    id: 5,
    card: {
      name: "MERCADO PAGO",
      avatar: "MERCADOPAGO",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 795,85",
    status: "cancel",
    action: null,
  },
  {
    id: 6,
    card: {
      name: "BRASILCARD",
      avatar: "BRASILCARD",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 145,12",
    status: "paid",
    action: null,
  },
  {
    id: 7,
    card: {
      name: "NEON [CRIS]",
      avatar: "NEON",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 145,12",
    status: "paid",
    action: null,
  },
  {
    id: 8,
    card: {
      name: "ATACADÃO",
      avatar: "ATACADAO",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 20,00",
    status: "due",
    action: null,
  },
  {
    id: 9,
    card: {
      name: "SANTANDER [2824]",
      avatar: "SANTANDER",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 20,00",
    status: "due",
    action: null,
  },
  {
    id: 10,
    card: {
      name: "RIACHUELO [CINT]",
      avatar: "RIACHUELO",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 145,12",
    status: "paid",
    action: null,
  },
  {
    id: 11,
    card: {
      name: "NUBANK [CINT]",
      avatar: "NUBANK",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 145,12",
    status: "paid",
    action: null,
  },
  {
    id: 12,
    card: {
      name: "NEON [CINT]",
      avatar: "NEON",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 145,12",
    status: "paid",
    action: null,
  },
  {
    id: 13,
    card: {
      name: "NEON [AUG]",
      avatar: "NEON",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 145,12",
    status: "paid",
    action: null,
  },
  {
    id: 14,
    card: {
      name: "NUBANK [AUG]",
      avatar: "NUBANK",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 145,12",
    status: "paid",
    action: null,
  },
  {
    id: 15,
    card: {
      name: "CAIXA [ANT]",
      avatar: "CAIXA",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 145,12",
    status: "paid",
    action: null,
  },
  {
    id: 16,
    card: {
      name: "NUBANK [CRIS]",
      avatar: "NUBANK",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 145,12",
    status: "paid",
    action: null,
  },
  {
    id: 17,
    card: {
      name: "OUZE",
      avatar: "OUZE",
      image: "/images/all-img/customer_1.png",
    },
    fechamento: "-",
    vencimento: "08/12/2024",
    valor: "R$ 145,12",
    status: "paid",
    action: null,
  }
];
